export const arrayDeProductos = [
  {
    id: 1,
    brand: "Harina de Trigo",
    size: "kg",
    price: 5000,
    description: "Harina de trigo para hacer la masa de pizza",
  },
  {
    id: 2,
    brand: "Tomate en Lata",
    size: "bolsas",
    price: 2000,
    description: "Tomate enlatado para salsa de pizza",
  },
  {
    id: 3,
    brand: "Mozzarella",
    size: "gramos",
    price: 8000,
    description: "Mozzarella fresca para cubrir la pizza",
  },
  {
    id: 4,
    brand: "Pepperoni",
    size: "gramos",
    price: 7000,
    description: "Pepperoni de alta calidad para pizza",
  },
  {
    id: 5,
    brand: "Aceitunas Negras",
    size: "bolsas",
    price: 3000,
    description: "Aceitunas negras para la pizza",
  },
  {
    id: 6,
    brand: "Salsa BBQ",
    size: "bolsas",
    price: 4000,
    description: "Salsa BBQ para pizza con pollo",
  },
  {
    id: 7,
    brand: "Levadura",
    size: "paquetes",
    price: 1500,
    description: "Levadura para hacer la masa de pizza",
  },
  {
    id: 8,
    brand: "Cebolla",
    size: "kg",
    price: 3000,
    description: "Cebolla fresca para la pizza",
  },
  {
    id: 9,
    brand: "Aceite de Oliva",
    size: "litros",
    price: 10000,
    description: "Aceite de oliva virgen para la pizza",
  },
  {
    id: 10,
    brand: "Jamón",
    size: "kg",
    price: 9000,
    description: "Jamón para la pizza hawaiana",
  },
  {
    id: 11,
    brand: "Pimiento Rojo",
    size: "kg",
    price: 3500,
    description: "Pimiento rojo fresco para la pizza",
  },
  {
    id: 12,
    brand: "Champiñones",
    size: "gramos",
    price: 6000,
    description: "Champiñones para la pizza vegetariana",
  },
  {
    id: 13,
    brand: "Salchichas",
    size: "gramos",
    price: 7500,
    description: "Salchichas para la pizza de salchichón",
  },
  {
    id: 14,
    brand: "Orégano",
    size: "gramos",
    price: 1000,
    description: "Orégano seco para condimentar la pizza",
  },
  {
    id: 15,
    brand: "Albahaca",
    size: "gramos",
    price: 1500,
    description: "Albahaca fresca para la pizza Margarita",
  },
  {
    id: 16,
    brand: "Queso Parmesano",
    size: "gramos",
    price: 2500,
    description: "Queso parmesano rallado para la pizza",
  },
  {
    id: 17,
    brand: "Bacon",
    size: "gramos",
    price: 5500,
    description: "Tiras de bacon para la pizza de bacon y huevo",
  },
  {
    id: 18,
    brand: "Pimientos Jalapeños",
    size: "gramos",
    price: 3000,
    description: "Pimientos jalapeños en rodajas para pizza picante",
  },
  {
    id: 19,
    brand: "Pechuga de Pollo",
    size: "kg",
    price: 12000,
    description: "Pechuga de pollo para la pizza de pollo BBQ",
  },
  {
    id: 20,
    brand: "Maíz",
    size: "gramos",
    price: 2500,
    description: "Maíz dulce para la pizza Hawaiana",
  },
  {
    id: 21,
    brand: "Salsa de Tomate",
    size: "bolsas",
    price: 3500,
    description: "Salsa de tomate casera para la pizza",
  },
  {
    id: 22,
    brand: "Chorizo",
    size: "gramos",
    price: 4500,
    description: "Chorizo picante para la pizza",
  },
  {
    id: 23,
    brand: "Aceitunas Verdes",
    size: "bolsas",
    price: 2500,
    description: "Aceitunas verdes rellenas para la pizza",
  },
  {
    id: 24,
    brand: "Piña en Lata",
    size: "bolsas",
    price: 3500,
    description: "Piña enlatada para la pizza Hawaiana",
  },
  {
    id: 25,
    brand: "Sal",
    size: "gramos",
    price: 1000,
    description: "Sal para sazonar la pizza",
  },
  {
    id: 26,
    brand: "Azúcar",
    size: "gramos",
    price: 1000,
    description: "Azúcar para equilibrar la acidez de la salsa de tomate",
  },
  {
    id: 27,
    brand: "Queso Cheddar",
    size: "gramos",
    price: 4000,
    description: "Queso cheddar para pizzas con queso extra",
  },
  {
    id: 28,
    brand: "Salsa de Barbacoa",
    size: "bolsas",
    price: 4000,
    description: "Salsa de barbacoa para la pizza de pollo BBQ",
  },
  {
    id: 29,
    brand: "Pan de Pizza",
    size: "paquetes",
    price: 3500,
    description: "Pan de pizza prelisto para hornear",
  },
  {
    id: 30,
    brand: "Tomate Cherry",
    size: "gramos",
    price: 4500,
    description: "Tomate cherry para la pizza de ensalada",
  },
];
